addons:
  apt:
    packages:
      - ghostscript
      - netpbm
      - sam2p
script:
  # generate
  - curl --remote-name --fail https://www.princexml.com/download/prince-11.3-linux-generic-x86_64.tar.gz
  - tar xzf prince-11.3-linux-generic-x86_64.tar.gz
  - echo ~/prince | ./prince-11.3-linux-generic-x86_64/install.sh
  - ~/prince/bin/prince -v https://html.spec.whatwg.org/ -o print.pdf
  - ls -l print.pdf
  # optimize
  # - curl --remote-name --fail https://downloads.sourceforge.net/project/multivalent/multivalent/Release20091027/Multivalent20091027.jar
  - ./pdfsizeopt/pdfsizeopt --do-require-image-optimizers=no print.pdf print-pdfsizeopt.pdf
  - ghostscript -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/printer -dNOPAUSE -dQUIET -dBATCH -sOutputFile=print-printer.pdf print.pdf
  - ghostscript -sDEVICE=pdfwrite -dCompatibilityLevel=1.4 -dPDFSETTINGS=/screen -dNOPAUSE -dQUIET -dBATCH -sOutputFile=print-screen.pdf print.pdf
  - ls -l *.pdf
