script:
  - curl --remote-name --fail https://www.princexml.com/download/prince-11.3-linux-generic-x86_64.tar.gz
  - tar xzf prince-11.3-linux-generic-x86_64.tar.gz
  - echo ~/prince | ./prince-11.3-linux-generic-x86_64/install.sh
  - curl --remote-name --fail https://downloads.sourceforge.net/project/multivalent/multivalent/Release20091027/Multivalent20091027.jar
