addons:
  apt:
    packages:
      - default-jre
      - fonts-dejavu
      - fonts-droid
      - netpbm
      - sam2p
script:
  # generate
  - curl --fail --remote-name https://www.princexml.com/download/prince-11.3-linux-generic-x86_64.tar.gz
  - tar xzf prince-11.3-linux-generic-x86_64.tar.gz
  - echo ~/prince | ./prince-11.3-linux-generic-x86_64/install.sh
  - ~/prince/bin/prince -v https://html.spec.whatwg.org/ -o print.pdf
  - ls -l print.pdf
  # optimize
  - export CLASSPATH="$PWD/Multivalent.jar"
  - ls -l $CLASSPATH
  - ./pdfsizeopt/pdfsizeopt --use-pngout=false --use-jbig2=false --use-multivalent=true print.pdf print-opt.pdf
  - ls -l *.pdf
